### ISSUE TITLE
HTML Special Chars

### ISSUE THREAD

**Issue by martoio** [jaylee66/prj-rev-bwfs-dasmoto#1]
Check out this article that explains why you need to care about using special characters in HTML: http://text-symbols.com/html/encode/

https://github.com/jaylee66/prj-rev-bwfs-dasmoto/blob/6f46755d8091b834154b91c224dc6c56ded97cbe/Dasmotos_Arts/index.html#L10

The ampersand should be written as:
``&amp;``

**Comment by jaylee66** [comment]
Resolved!
