### ISSUE TITLE
Accessiility

### ISSUE THREAD

**Issue by martoio** [jaylee66/prj-rev-bwfs-dasmoto#4]
Make sure you add the ``alt`` attribute to your images to maintain accessibility for all audiences of the page (particularly visually-impaired users). 
For more info: https://www.codecademy.com/articles/accessibility

https://github.com/jaylee66/prj-rev-bwfs-dasmoto/blob/6f46755d8091b834154b91c224dc6c56ded97cbe/Dasmotos_Arts/index.html#L15

**Comment by jaylee66** [comment]
resolved
